config/routes.rb
Gitpeach::Application.routes.draw do
  post "login"  => "sessions#create" , as: :login
  get  "logout" => "sessions#destroy", as: :logout

  root 'top#index'

  resources :kanbans, constraints: { id: /[a-zA-Z.0-9_\-]+\/[a-zA-Z.0-9_\-]+/ }, only: [:show, :create, :destroy, :edit, :update], path: "/" do
    member do
      get :sync
    end

    resources :issues, constraints: {id: /\d+/}, only: [:show, :update, :create] do
    end
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    if current_user
      projects = current_user.projects
      @user_kanban_projects = projects.select{|project| Kanban.exists?(gitlab_project_id: project.id) }
      @no_kanban_projects   = projects.reject{|project| Kanban.exists?(gitlab_project_id: project.id) }

      user_project_ids = @user_kanban_projects.map(&:id)
      @other_kanbans = Kanban.where.not(gitlab_project_id: user_project_ids)
    end
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/top/_logged_in.html.slim
- unless @user_kanban_projects.empty?
  h1 Your Kanbans

  table.table
    tbody
      - @user_kanban_projects.each do |project|
        tr
          td
            = link_to kanban_path(project.path_with_namespace) do
              = project.path_with_namespace
          td
            = link_to kanban_path(project.path_with_namespace), class: "btn btn-default" do
              span.glyphicon.glyphicon-tasks
              | Show
            = link_to edit_kanban_path(project.path_with_namespace), class: "btn btn-default" do
              span.glyphicon.glyphicon-wrench
              | Edit
            = link_to project.path_with_namespace, data: {:confirm => 'Are you sure?'}, class: "btn btn-danger", method: :delete do
              span.glyphicon.glyphicon-trash
              | Destroy

- unless @other_kanbans.empty?
  h1 Other Kanbans

  table.table
    tbody
      - @other_kanbans.each do |kanban|
        tr
          td
            = link_to kanban_path(kanban) do
              = kanban.name
          td
            = link_to kanban_path(kanban), class: "btn btn-default" do
              span.glyphicon.glyphicon-tasks
              | Show


- unless @no_kanban_projects.empty?
  h1 Your Projects

  table.table
    tbody
      - @no_kanban_projects.each do |project|
        tr
          td
            = link_to project.path_with_namespace, project.web_url
          td
            = form_tag kanbans_path
              = hidden_field_tag "kanban[gitlab_project_id]", project.id
              = hidden_field_tag "kanban[name]", project.path_with_namespace
              = button_tag type: "submit", class: "btn btn-primary" do
                span.glyphicon.glyphicon-file
                | Create Kanban

app/views/top/_not_logged_in.html.slim
= link_to "https://github.com/sue445/gitpeach" do
  = image_tag "https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png", alt: "Fork me on GitHub", style: "position: absolute; top: 0; right: 0; border: 0;"

h1 Gitpeach

- gitlab_url = Gitlab.endpoint.gsub(%r{/api/.+}, "/")

.alert.alert-info
  | Input username/password of
  | &nbsp;
  = link_to(gitlab_url, gitlab_url)

= form_tag login_path, class: "form-horizontal" do
  = hidden_field_tag :back_to, params[:back_to]
  .form-group
    label for="login" class="col-sm-2 control-label"
      | Login
    .col-sm-8
      = text_field_tag :login, nil, class: "form-control"
  .form-group
    label for="password" class="col-sm-2 control-label"
      | Password
    .col-sm-8
      = password_field_tag :password, nil, class: "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      = button_tag type: "submit", class: "btn btn-default" do
        | Login with Gitlab

coffee:
  $(document).ready ->
    $("#login").focus()

app/views/top/index.html.slim
- if logged_in?
  = render partial: "logged_in"
- else
  = render partial: "not_logged_in"