config/routes.rb
Gitpeach::Application.routes.draw do
  post "login"  => "sessions#create" , as: :login
  get  "logout" => "sessions#destroy", as: :logout

  root 'top#index'

  resources :kanbans, constraints: { id: /[a-zA-Z.0-9_\-]+\/[a-zA-Z.0-9_\-]+/ }, only: [:show, :create, :destroy, :edit, :update], path: "/" do
    member do
      get :sync
    end

    resources :issues, constraints: {id: /\d+/}, only: [:show, :update, :create] do
    end
  end

end

app/models/kanban.rb
# == Schema Information
#
# Table name: kanbans
#
#  id                :integer          not null, primary key
#  gitlab_project_id :integer
#  name              :string(255)
#  slug              :string(255)
#  created_at        :datetime
#  updated_at        :datetime
#
# Indexes
#
#  index_kanbans_on_name  (name) UNIQUE
#  index_kanbans_on_slug  (slug) UNIQUE
#

class Kanban < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :labels, -> { order(:disp_order) }, dependent: :destroy

  after_create :create_default_labels

  def normalize_friendly_id(text)
    text
  end

  # @return [Hash] key: label_id, value: issues
  def issues_group_by_label(issues)
    issues ||= []
    issues.group_by{|issue| issue_label_id(issue) }
  end

  def label_groups(issues)
    issues_group_by_label = self.issues_group_by_label(issues)
    done_label = self.labels.done.first

    label_groups = []
    self.labels.each do |label|
      issues = issues_group_by_label[label.id] || []
      if label == done_label
        # reject old closed tasks
        issues = issues.reject{|issue| issue.updated_at < 1.week.ago }
      end

      label_groups << {
          label:  label,
          issues: issues
      }
    end

    label_groups
  end

  # @return [Integer] label_id
  def issue_label_id(issue)
    if issue.state == "closed"
      self.labels.done.first.id
    else
      not_backlog_label = self.labels.other.where(gitlab_label: issue.labels).first
      not_backlog_label ? not_backlog_label.id : self.labels.backlog.first.id
    end
  end

  # @param gitlab_labels   [Array<String>]
  # @param from_label_id   [Integer]
  # @param to_label_id     [Integer]
  # @return [Array<String>]
  def update_gitlab_issue_labels(gitlab_labels, from_label_id, to_label_id)
    from_label = self.labels.find(from_label_id)
    to_label   = self.labels.find(to_label_id)

    updated_labels = []
    updated_labels << to_label.gitlab_label if from_label.is_backlog_issue? || from_label.is_close_issue?

    gitlab_labels.each do |gitlab_label|
      if gitlab_label == from_label.gitlab_label
        updated_labels << to_label.gitlab_label
      else
        updated_labels << gitlab_label
      end
    end

    updated_labels.compact
  end

  def gitlab_issue_state(from_label_id, to_label_id)
    from_label = self.labels.find(from_label_id)
    to_label   = self.labels.find(to_label_id)

    if from_label.opened? && to_label.closed?
      "close"
    elsif from_label.closed? && to_label.opened?
      "reopen"
    else
      # send "open" to "opened" issue (or send "close" to "closed" issue), 404 error at gitlab v6.4.3
      nil
    end
  end

  private
  def create_default_labels
    Label::DEFAULTS.each_with_index do |params, index|
      labels.create(params.merge(disp_order: index))
    end
  end
end

app/controllers/kanbans_controller.rb
class KanbansController < ApplicationController
  before_action :set_kanban, only: [:show, :destroy, :edit, :update, :sync]

  unless Rails.env.test?
    before_action :authenticate_user
    before_action :set_user_kanban, only: [:show, :sync]
  end

  # GET /:id
  # GET /:id.json
  def show
    @label_groups = @kanban.label_groups(project_issues)
  end

  # GET /:id/edit
  def edit
    @labels = @kanban.labels.map{|label| label.attributes.with_indifferent_access }
  end

  # POST /:id
  # POST /:id.json
  def create
    @kanban = Kanban.new(kanban_params)

    respond_to do |format|
      if @kanban.save
        format.html { redirect_to @kanban, notice: 'Kanban was successfully created.' }
        format.json { render action: 'show', status: :created, location: @kanban }
      else
        format.html { render action: 'new' }
        format.json { render json: @kanban.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /:id
  # PATCH/PUT /:id.json
  def update
    is_all_success = true

    Label.transaction do
      param_label_ids = params[:labels].inject([]){|array, label_params| array << label_params[:id]; array }.compact.map(&:to_i)
      @kanban.labels.each do |label|
        label.destroy unless param_label_ids.include?(label.id)
      end

      labels_params[:labels].each_with_index do |label_params, index|
        # for checked -> unchecked
        label_params[:is_backlog_issue] = false unless label_params.has_key?(:is_backlog_issue)
        label_params[:is_close_issue]   = false unless label_params.has_key?(:is_close_issue)

        label_params[:disp_order] = index
        if label_params[:id].blank?
          label = @kanban.labels.build(label_params)
          is_all_success &= label.save
        else
          label = @kanban.labels.find(label_params[:id])
          is_all_success &= label.update(label_params.reject{|k,v| k == :id })
        end

        label.errors.each do |attribute, error|
          @kanban.errors[attribute] = error
        end
      end
    end

    if is_all_success
      redirect_to edit_kanban_path(@kanban), notice: 'Kanban was successfully updated.'
    else
      @labels = params[:labels]
      render action: 'edit'
    end
  end

  # DELETE /:id
  # DELETE /:id.json
  def destroy
    @kanban.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

  # GET /:id/sync
  def sync
    @kanban.gitlab_project_id = @user_kanban.project.id
    @kanban.name              = @user_kanban.project.path_with_namespace
    @kanban.slug              = nil

    if @kanban.save
      redirect_to edit_kanban_path(@kanban), notice: 'Kanban was synchronized with Gitlab.'
    else
      redirect_to edit_kanban_path(@kanban), error: 'Failed synchronized with Gitlab.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kanban
      @kanban = Kanban.friendly.find(params[:id])
    end

    def set_user_kanban
      @user_kanban = UserKanban.new(current_user, @kanban) if current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kanban_params
      params.require(:kanban).permit(:gitlab_project_id, :name)
    end

    def labels_params
      params.permit(labels: [:name, :gitlab_label, :is_backlog_issue, :is_close_issue, :disp_order, :id])
    end

    def project_issues
      @user_kanban.issues
    end
end

app/helpers/kanbans_helper.rb
module KanbansHelper
end

app/views/kanbans/edit.html.slim
h1
  | Editing kanban

  = link_to sync_kanban_path, class: "btn btn-default btn-xs help-tooltip", "data-toggle"=>"tooltip", title: "Sync with Gitlab (if changed repository name, click this)" do
    span.glyphicon.glyphicon-refresh

  = button_tag :add_label, type: "button", class: "btn btn-default btn-xs", id: :add_label do
    span.glyphicon.glyphicon-plus

- if @kanban.errors.any?
  #error_explanation.alert.alert-warning
    h4 = "#{pluralize(@kanban.errors.count, "error")} prohibited this kanban from being saved:"
    ul
      - @kanban.errors.full_messages.each do |message|
        li = message

= form_tag kanban_path, id: "update_kanban", method: :put do
  ul.list-group
    - @labels.each do |label|
      li.edit_label.list-group-item
        i.glyphicon.glyphicon-align-justify.drag-column
        = hidden_field_tag "labels[][id]", label[:id]
        = text_field_tag "labels[][name]", label[:name], id: nil, placeholder: "name"
        = text_field_tag "labels[][gitlab_label]", label[:gitlab_label], id: nil, placeholder: "gitlab label"

        label.btn.btn-success
          = radio_button_tag "labels[][is_backlog_issue]", true, label[:is_backlog_issue], id: nil
          | Backlog Issue
        = link_to "#", "data-toggle"=>"tooltip", title: "Check to display all open issues in this column", class: "help-tooltip" do
          span.glyphicon.glyphicon-question-sign

        label.btn.btn-warning
          = radio_button_tag "labels[][is_close_issue]", true, label[:is_close_issue], id: nil
          | Close Issue
        = link_to "#", "data-toggle"=>"tooltip", title: "Check to close an issue on Gitlab when a card is dragged into this column", class: "help-tooltip" do
          span.glyphicon.glyphicon-question-sign

        = button_tag :delete_label, type: "button", class: "btn btn-danger delete_label", id: nil do
          span.glyphicon.glyphicon-trash

  div
    = button_tag :submit_button, class: "btn btn-primary" do
      span.glyphicon.glyphicon-floppy-save
      | Save

    = link_to kanban_path, class: "btn btn-default" do
      | Back


= javascript_include_tag "kanbans_edit"


/ if append line, copied DOM
ul#hidden_list
  li.edit_label.list-group-item
    i.glyphicon.glyphicon-align-justify.drag-column
    = hidden_field_tag "labels[][id]", nil
    = text_field_tag "labels[][name]", nil, id: nil, placeholder: "name"
    = text_field_tag "labels[][gitlab_label]", nil, id: nil, placeholder: "gitlab label"

    label.btn.btn-success
      = radio_button_tag "labels[][is_backlog_issue]", true, nil, id: nil
      | Backlog Issue
    = link_to "#", "data-toggle"=>"tooltip", title: "Check to display all open issues in this column", class: "help-tooltip" do
      span.glyphicon.glyphicon-question-sign

    label.btn.btn-warning
      = radio_button_tag "labels[][is_close_issue]", true, nil, id: nil
      | Close Issue
    = link_to "#", "data-toggle"=>"tooltip", title: "Check to close an issue on Gitlab when a card is dragged into this column", class: "help-tooltip" do
      span.glyphicon.glyphicon-question-sign

    = button_tag :delete_label, type: "button", class: "btn btn-danger delete_label", id: nil do
      span.glyphicon.glyphicon-trash

app/views/kanbans/show.html.slim
- content_for :title, @kanban.name


h1
  = link_to @kanban.name, @user_kanban.project.web_url
  = link_to edit_kanban_path, class: "btn btn-default btn-xs" do
    span.glyphicon.glyphicon-wrench

= hidden_field_tag :label_groups_count, @label_groups.count

form.form-inline#create_issue_form role="form"
  .form-group
    = text_field_tag :new_issue_title, nil, class: "form-control", placeholder: "issue title", size: 50
  button.btn.btn-primary#create_issue_button type="submit"
    span.glyphicon.glyphicon-plus
    | New Issue

  = image_tag "loading.gif", id: "loading", style: "display: none"

.row
  - @label_groups.each do |label_group|
    - label  = label_group[:label]
    - issues = label_group[:issues]
    .label-area
      h3
        - if label.is_backlog_issue?
          span.glyphicon.glyphicon-tasks
        - if label.is_close_issue?
          span.glyphicon.glyphicon-ok

        = label.name
        span.badge id="count_#{label.id}"
          = issues.count

      div.well.label-column id="label_#{label.id}"
        = render partial: "shared/issue_panel", collection: issues, as: :issue

= hidden_field_tag :kanban_name, @kanban.name
= hidden_field_tag :pusher_key , Pusher.key
= hidden_field_tag :channel    , "kanban_#{@kanban.id}"

= javascript_include_tag "http://js.pusher.com/2.1/pusher.min.js"

- unless Rails.env.production?
  coffee:
    window.Pusher.log = (message) ->
      window.console.log(message) if window.console && window.console.log

= javascript_include_tag "kanbans_show"